# site name
siteName: 觅古寻中
shortName: 觅


# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: false

# favicon
favicon: /images/favicon.png
# unique avatar
avatarShow: true
avatarImage: /img/avatar.jpg

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10


# your site build time or domain buy time
siteBuildingTime: 11/30/2017


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   前端: big-front-end
   后台: server-side
   设计: design
   资源: resource

# Left menu of single pages settings
## Notice: faName is FontAwesome style name
leftPagesMenu:
- uri: cross_fire
  title: 穿越火线
  faName: fa-wifi
- uri: help
  title: 急救中心
  faName: fa-question-circle


# cover info config
coverTitle: 追寻中医内涵的文化之美
coverDescription: Chase TCM即Chinese Ancient Shining Enchantment of TCM的缩写，Chase取寻觅之意，对应品牌的中文名称“觅古寻中”——追寻中医内涵的文化之美。

# sns url
sns:
 # telegram: http://t.me/codeist
 # instagram: https://www.instagram.com/coder.thomas/
 # twitter: https://twitter.com/tangkunyin
 # github: https://github.com/tangkunyin

# your article copyright or content declare
postDeclare: 本文内容仅作为作者个人兴趣与观点，不代表所在公司及团队的观点和决策。若有不恰当之处，望不吝赐教

# Git-pages server info
pageServerName: Coding
pageServerUrl: https://coding.net/register?key=bcace447-fa41-4579-9783-86fdf0f723e2


## Comments settings.You can choose only ONE to display.
# disqus shortName,
disqus_shortname:
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: false
  githubID: 
  repo: 
  ClientID: 
  ClientSecret: 
  lazy: true
